config/routes.rb
CarrierApp::Application.routes.draw do

  post "/users" => "users#create"
  get "/users/sign_out" => "sessions#destroy"

  devise_for :users, :controllers => {:registrations => 'registrations', sessions: "sessions" }
  
  devise_scope :user do
    match "/users/sign_in.:format" => "sessions#create", via: :options
    get "/users/sign_in.:format" => "sessions#create"
  end

  

    root 'home#index'
    resources :invitations
    resources :users do 
      collection do
        get 'add_user'
        post 'adduser'
      end
    end

    resources :customers do
      member do
        get 'users'
        get 'assign_customer'
        get 'unassign'
        get 'close_customer'
      end
      collection do 
        get 'closedCustomers'
        post 'add_users'
      end
      resources :items do 
        member do
          patch 'upload_image'
        end
        collection do
          get 'empty_item'
        end
      end
    end

    
    resources :questions, only: [:index] do
      member do
        get 'get_question'
      end
      resources :reports, only: [] do 
        member do
          get 'get_answer'
          get 'getanswerid'
        end
      end
    end
    resources :categories, only: [:index] do 
      member do
        get 'questions'
      end
    end
    resources :projects do
      member do 
        get 'detail_report'
        get 'assign_project'
        get 'report'
        get 'users'
        get 'unassign'
        get 'submit_report'
        patch 'update_answer'
        get 'categories'
        get 'checklist'
      end
      collection do 
        post 'add_users'
      end
      resources :answers, only: [:update] do
        member do
           patch 'update_answer'
           get 'check_answer'  
        end
      end
      resources :reports do 
        member do
          get 'detail_report'
        end
      end
      resources :incidents, only: [:new, :create, :index, :show]
    end

    resources :reports, only: [] do
      member do
        get 'answers'
      end 
      resources :categories, only: [] do
        member do
          get 'answers'
        end
      end
    end

    resources :incidents, only: [] do
      member do 
        get 'send_new_incident'
        post 'send_email'
        get 'send_email'
      end
    end

end

app/models/answer.rb
class Answer < ActiveRecord::Base

	belongs_to :question
	# belongs_to :project
	belongs_to :report
	mount_uploader :file, FileUploader
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :questions
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	belongs_to :creator, class_name: "User"
	# belongs_to :user
	has_and_belongs_to_many :users
	has_many :items
	attr_accessor :userid, :city,:state,:zip,:city1,:state1,:zip1 
end

app/models/customers_user.rb
class CustomersUser < ActiveRecord::Base
end

app/models/incident.rb
class Incident < ActiveRecord::Base
	belongs_to :project

	validates_presence_of :report_type
	validates_presence_of :your_name
	validates_presence_of :job_title
	validates_presence_of :injury_date
	validates_presence_of :injury_time
	validates_presence_of :location
	validates_presence_of :injuries_type

	mount_uploader :file, FileUploader

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
	belongs_to :user
	validates :email, presence: true, :uniqueness => true
	attr_accessor :password

  
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :customer

	mount_uploader :file1, FileUploader
	mount_uploader :file2, FileUploader
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :creator, class_name: "User"
	# belongs_to :user
	has_and_belongs_to_many :users
	# has_many :answers, dependent: :destroy
	has_many :reports,dependent: :destroy
	has_many :incidents, dependent: :destroy
	
	validates_presence_of :address
	validates_presence_of :contact_info
	attr_accessor :userid
	
	after_create :create_answers
  	
  	def create_answers
  		# report = self.reports.build
  		# # report.name = Date.today.to_s
  		# report.name = "#{self.name} Report #{Date.today.to_s}"
  		# report.save!
	   #  Question.all.each do |q|
	   #    # report.answers.create!(question_id: q.id)
	   #    # report.answers << Answer.create!(question_id: q.id)
	   #    Answer.create!(question_id: q.id, report_id: report.id, file: nil)	
	    # end
  	end
end

app/models/projects_users.rb
class ProjectsUsers < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :category
	has_many :answers

end

app/models/report.rb
class Report < ActiveRecord::Base

	belongs_to :project
	has_many :answers, dependent: :destroy
end

app/models/token.rb
class Token < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :first_name       



  has_many :tokens
  has_many :invitations 
  # has_many :projects
  # has_and_belongs_to_many :projects
  has_and_belongs_to_many :customers

  # has_many :created_projects, class_name: "Project", foreign_key: "creator_id"
  has_many :created_customers, class_name: "Customer", foreign_key: "user_id"
  has_many :subordinates, class_name: "User", foreign_key: "client_id"
  belongs_to :client, class_name: "User"
 
  def whole_customers
  	self.customers.where(close: false)
  end

  def closed_customers
    self.customers.where(close: true)
  end

  def admin?
    self.role == "admin"
  end
  def client?
    self.role == "client"
  end
  # def password
  #   key = "helloworld123"
  #   encrypted_data = read_attribute(:password)
  #   AESCrypt.decrypt(encrypted_data, key)
  # end

  # def password=(pwd)
  #   key = "helloworld123"
  #   encrypted_data = AESCrypt.encrypt(pwd, key)
  #   write_attribute(:password, encrypted_data)
  # end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

	def answer_radio_status(ans_st, current_st)
		ans_st == current_st
	end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carrier App</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <% if current_user.present? %>
  	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <% else %>
  	<%= javascript_include_tag "landing", "data-turbolinks-track" => true %>
  <% end %>	
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: "partials/nav_bar" if current_user.present? %>
<%= render partial: "partials/landing_nav_bar" unless current_user.present? %>
<%= render partial: "partials/flash_message" %>
<div class="container" >
	<%= yield %>
</div>

</body>
</html>

app/views/partials/_flash_message.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
  	<% name = name.to_s == 'notice' ? 'success' : name.to_s %>
  	<% name = name.to_s == 'alert' ? 'danger' : name.to_s %>
    <div class="alert alert-<%= name %> main-alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg.html_safe, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/partials/_landing_nav_bar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><img src="https://www.google.com.pk/images/srpr/logo11w.png"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= new_user_session_path %>">sign in</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  
</nav>

app/views/partials/_nav_bar.html.erb
<script type="text/javascript">
  $(document).ready(function(){
      $("."+ $("#active_class").val()).addClass("active");
        // $(".active_class").removeClass("active");
        // $(this).addClass("active");
  });
</script>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><img src="https://www.google.com.pk/images/srpr/logo11w.png"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <% if current_user.role == 'client' %>
        <li class="invitations"><a href="<%= users_path %>">List users</a></li>
        <li class="invite_user"><a href="<%= new_user_path %>">Add user</a></li>

        
        
      <% elsif current_user.role == "admin" %>
        <li class="invitations"><a href="<%= users_path %>">List carriers</a></li>
        <li class="invite_user"><a href="<%= new_user_path %>">Add carriers</a></li>
      <% end %>
      <% unless current_user.role == 'admin' %>
        <li class="invitations"><a href="<%= customers_path %>">Existing customers</a></li>
        <li class="invite_user"><a href="<%= new_customer_path %>">Add customer</a></li>
        <li class="invite_user"><a href="<%= closedCustomers_customers_path %>">Cloased customers</a></li>
      <% end %>   
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to  current_user.email, edit_user_path(current_user) %></li>
          <li><%#= link_to 'Destroy', project, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-sm btn-danger" %>
          <a href="<%= destroy_user_session_path %>" data-method="delete">Log out</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>