config/routes.rb
CarrierApp::Application.routes.draw do

  post "/users" => "users#create"
  get "/users/sign_out" => "sessions#destroy"

  devise_for :users, :controllers => {:registrations => 'registrations', sessions: "sessions" }
  
  devise_scope :user do
    match "/users/sign_in.:format" => "sessions#create", via: :options
    get "/users/sign_in.:format" => "sessions#create"
  end

  

    root 'home#index'
    resources :invitations
    resources :users do 
      collection do
        get 'add_user'
        post 'adduser'
      end
    end

    resources :customers do
      member do
        get 'users'
        get 'assign_customer'
        get 'unassign'
        get 'close_customer'
      end
      collection do 
        get 'closedCustomers'
        post 'add_users'
      end
      resources :items do 
        member do
          patch 'upload_image'
        end
        collection do
          get 'empty_item'
        end
      end
    end

    
    resources :questions, only: [:index] do
      member do
        get 'get_question'
      end
      resources :reports, only: [] do 
        member do
          get 'get_answer'
          get 'getanswerid'
        end
      end
    end
    resources :categories, only: [:index] do 
      member do
        get 'questions'
      end
    end
    resources :projects do
      member do 
        get 'detail_report'
        get 'assign_project'
        get 'report'
        get 'users'
        get 'unassign'
        get 'submit_report'
        patch 'update_answer'
        get 'categories'
        get 'checklist'
      end
      collection do 
        post 'add_users'
      end
      resources :answers, only: [:update] do
        member do
           patch 'update_answer'
           get 'check_answer'  
        end
      end
      resources :reports do 
        member do
          get 'detail_report'
        end
      end
      resources :incidents, only: [:new, :create, :index, :show]
    end

    resources :reports, only: [] do
      member do
        get 'answers'
      end 
      resources :categories, only: [] do
        member do
          get 'answers'
        end
      end
    end

    resources :incidents, only: [] do
      member do 
        get 'send_new_incident'
        post 'send_email'
        get 'send_email'
      end
    end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	belongs_to :creator, class_name: "User"
	# belongs_to :user
	has_and_belongs_to_many :users
	has_many :items
	attr_accessor :userid, :city,:state,:zip,:city1,:state1,:zip1 
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	before_action :authenticate_user!
	before_action :check_user
	# before_action :set_project, only: [:edit, :update, :destroy, :detail_report]
	respond_to :html, :json, only: [:closedCustomers,:index, :new, :create, :edit, :update, :show, :destroy,:assign_project,:add_users,:reports,:users]

	def index
		@customers = current_user.whole_customers
		respond_with @customers
	end

	def closedCustomers
		@customers = current_user.closed_customers
		respond_with @customers
	end

	def new
		@customer = Customer.new
		# respond_with @customer
	end

	def create
		puts "----"*90
		user_client = current_user.client
		params[:customer][:creator_id] = current_user.id 
		customer = user_client.customers.build(params_customer)
		# if customer.save
		cus_user = CustomersUser.new
		cus_user.user_id = current_user.id
		cus_user.customer_id = customer.id
		cus_user.save!
		# flash[:success] = "Customer successfully created."
		# redirect_to user_customers_path(current_user)
		respond_to do |format|
			if customer.save
				create_address(params,customer)
				if current_user.role == "client"
					users = params[:customer][:userid] if params[:customer][:userid].present?
					users && users.each do |user|
						if user != ""
							cus_user = CustomersUser.new
							cus_user.user_id = user.to_i
							cus_user.customer_id = customer.id
							cus_user.save!
						end	
					end
				end
				cus_user = CustomersUser.where(user_id:current_user.id, customer_id: customer.id).first || CustomersUser.new
				cus_user.user_id = current_user.id
				cus_user.customer_id = customer.id
				cus_user.save!
				# flash[:notice] = "Project was successfully created." 
				format.html { redirect_to customers_path, success: "Customer successfully created." }
		        format.json {  render json: :true} 
			else
		        format.html { render action: 'new' }
		        format.json { render json: :false}
		        # format.json { render json: @incident.errors, status: :unprocessable_entity }
		    end
	    end
	end

	

	def edit
		@customer = Customer.find(params[:id])
		address = @customer.loading_address.split(', ')

		@customer.loading_address = address[0]
		@customer.city = address[1]
		@customer.state = address[2]
		@customer.zip = address[3]

		des_address = @customer.destination_address.split(', ')
		@customer.destination_address = des_address[0]
		@customer.city1 = des_address[1]
		@customer.state1 = des_address[2]
		@customer.zip1 = des_address[3]
		
		respond_with @customer
	end

	def update
		puts "===="*90
		@customer = Customer.find(params[:id])
    	flash[:notice] = 'Customer was successfully updated.' if @customer.update(params_customer)
    	create_address(params,@customer)
    	return render json: :true	
	end

	def users
		@customer = Customer.find(params[:id])
		@users = @customer.users
		respond_with @users
	end

	def close_customer
		customer = Customer.find(params[:id])
		customer.close = true
		customer.close_date = DateTime.now
		customer.save!				
		respond_to do |format|
	        format.html { redirect_to customers_path, notice: "#{customer.name} successfully closed." }
	        format.json { render :json=> true }
	    end
	end


	def assign_customer
		@customer = Customer.find(params[:id])
		@users = current_user.subordinates
		# respond_with @project
	end

	def unassign
		@customer = Customer.find(params[:id])
		cust_user = CustomersUser.where(customer_id: @customer.id, user_id: params[:uid]).first
		cust_user.destroy if cust_user.present?
		flash[:success] = "Unassigned successfully."
		redirect_to customer_path
	end

	def add_users
		
		id = params[:customerid]
		users = params[:customer][:userid] if params[:customer][:userid].present?
		customer = Customer.find(id)
		users && users.each do |user|
			if user != ""
				customer_user =  CustomersUser.where(user_id: user , customer_id: id).first || CustomersUser.new
				customer_user.user_id = user.to_i
				customer_user.customer_id = id.to_i
				customer_user.save!	
			end	
		end
		# respond_with project_user
		respond_to do |format|
	        format.html { redirect_to customers_path, notice: 'Users add successfully.' }
	        format.json { render :json=> true }
	    end
		# flash[:success] = "Users add successfully"
		# redirect_to projects_path		
	end

	def show
		@customer = Customer.find(params[:id])
	end



	private

	def params_customer
		params.require(:customer).permit(:creator_id,:name, :phone, :bill_of_laden, :loading_address, :destination_address, :tag_lot_number,:tag_lot_color,:agent_name,:date_of_pickup,:charges,:userid,:city,:state,:zip,:city1,:state1,:zip1)
	end

	def check_user
		# puts "11111"*90
		if current_user.role == 'admin'
			# puts "0000"*90
			flash[:notice] = 'You are not Authorise'
			return redirect_to root_url
		end	
	end	

	def create_address(params,customer)
		loading_address = [params[:customer][:loading_address], params[:customer][:city], params[:customer][:state], params[:customer][:zip]].join(", ")
		destination_address = [params[:customer][:destination_address], params[:customer][:city1], params[:customer][:state1], params[:customer][:zip1]].join(", ")
		customer.loading_address = loading_address
		customer.destination_address = destination_address
		customer.save!
	end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_notes.html.erb
<style type="text/css">
	.div{
		width: 25%;
		background-color: lightgreen;
		margin-left: 0%;	
	}
	.mybutton{
		margin-top: -1px;
		margin-right: 74%;
		margin-bottom: 24px;
	}
	.file{
		margin-top: 11px;
	}
</style>

<%= form_for @answer1,:url=>update_answer_project_path(@answer1), remote: :true, html: {id: "#{@answer1.id}-answer",role: 'form' ,method: :patch , multipart: true} do |f| %>

		<%= f.hidden_field  "answer-#{@answer1.id}", value: @answer1.id %>
		<%= f.hidden_field :project, value: @project.id %>

		<div class="row">
			<%= f.text_area :notes,:cols => 35, :rows => 3, :id=>"notes-#{@answer1.id}"  %>
			<%= f.file_field :file, :class=>"file" %>
			<div class='div hidden save-span-<%="#{@answer1.id}"%>' styule="color: red;">Successfully saved.</div>
	 		<button id='<%= "#{@answer1.id}" %>' class='btn btn-primary btn-xs update-answer mybutton pull-right'>submit</button>
	 	</div>		
<% end %>

app/views/customers/assign_customer.html.erb
<script type="text/javascript">
  $(document).ready(function(){
    $('#customer_userid').multiselect();
  });
</script>
<%#= hidden_field_tag 'active_class', 'create_project'%>
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
  <h1><%= @customer.name %></h1>
    <%= form_for @customer,:url=>add_users_customers_path, html: { class: 'well form-horizontal', role: 'form', method: :post} do |f| %>
      <%= hidden_field_tag 'customerid', @customer.id %>
      <fieldset>
        <% if @customer.errors.any? %>
          <div class="alert alert-danger">
            <h4><%= pluralize(@customer.errors.count, "error") %> prohibited this project from being saved:</h4>

            <ul>
            <% @customer.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
  
        <% if current_user.role == "client" %>
          <div class="form-group">
            <%= f.label :cars, "Add user", class: "col-sm-3 control-label" %>
            <div class="col-sm-9">
              <%= f.select(:userid, options_for_select(current_user.subordinates.collect {|x| [x.email, x.id]}), {}, {multiple: "multiple"}) %>
            </div>
          </div>
        <% end %>
      </fieldset>

      <div class="col-sm-offset-3">
        <%= f.submit 'Save', class: "btn btn-primary" %>

      </div>
    <% end %>
  </div>
</div>

app/views/customers/categories.html.erb
<div class="alert alert-info">
  <strong>Project:</strong> <%= @project.name %>
</div>
<h3>Category List</h3>
<table class="table table-bordered table-striped table-condensed">
  <thead>
    <th>#</th>
    <th>Category Name</th>
  </thead>  
  <tbody>
    <% @categories.each_with_index do |cat,index|%>
      <tr>
        <td><%= index+1 %></td>
        <td><%= link_to cat.name, checklist_project_path(@project, {cat: cat.id})%></td>
        </tr>
    <% end %>   
  </tbody>  
</table> 
<!-- project_path(@project, {cat: cat.id}) -->

app/views/customers/checklist.html.erb
<div class="alert alert-info">
  <strong>Projects:</strong> <%= @project.name %>
</div>
<h3>Checklists</h3>
<table class="table table-bordered table-striped table-condensed">
  <thead>
    <th>#</th>
    <th>Checklist Name</th>
  </thead>  
  <tbody>
    <% @reports.each_with_index do |rep,index|%>
      <tr>
        <td><%= index+1 %></td>
        <td><%= link_to rep.name, project_path(@project, {cat: @category, rep: rep.id})%></td>
        </tr>
    <% end %>   
  </tbody>  
</table> 
<!-- project_path(@project, {cat: cat.id}) -->

app/views/customers/closedCustomers.html.erb
<script type="text/javascript">
  $(document).ready(function(){

    if ( $('#inc_id').length > 0 && $('#inc_id').val() > 0 ){
      window.location.href = '/incidents/'+ $('#inc_id').val() +'/send_new_incident.pdf';
    }

  });  
</script>
<%= hidden_field_tag 'active_class', 'all_projects'%>
<% if @customers.present? %>  
  <%#= link_to "Reports", report_projects_path, class: "btn btn-sm btn-info pull-right" ,style: "margin-bottom: 8px;"%>
  <h1>Customer List</h1>
  <table class="table table-bordered table-striped table-condensed">
    <thead>
      <th>Customer Name</th>
      <th>Contact Info</th>
      <!-- <th>Address</th> -->
      <th>Action</th>
    </thead>  
    <tbody>
      <% @customers.each do |customer|%>
        <tr>
          <td><%= link_to customer.name, customer_items_path(customer)%></td>
          <td><%= customer.phone %></td>
          <td>
            
            <%= link_to "users", users_customer_path(customer), class: "btn btn-xs btn-default" %>
            <!-- users_project_path(project) -->
            <%= link_to "View items",customer_items_path(customer), class: "btn btn-xs btn-success" %>
  
            <%#= link_to 'Delete', project, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-xs btn-danger" %>
            </td>
        </tr>
      <% end %>   
    </tbody>  
  </table> 
<% else %>
  <b>No Customer Present</b>
<% end %>   

app/views/customers/edit.html.erb
<h1 class = "text-center">Edit Customer</h1>
<%= link_to '<< Back', customer_path(@customer), :class=>"btn btn-primary btn-xs" %>
<%= render "form", :url=>customer_path(@customer) %> 

app/views/customers/index.html.erb
<script type="text/javascript">
  $(document).ready(function(){

    if ( $('#inc_id').length > 0 && $('#inc_id').val() > 0 ){
      window.location.href = '/incidents/'+ $('#inc_id').val() +'/send_new_incident.pdf';
    }

  });  
</script>
<%= hidden_field_tag 'active_class', 'all_projects'%>
<% if @customers.present? %>  
  <%#= link_to "Reports", report_projects_path, class: "btn btn-sm btn-info pull-right" ,style: "margin-bottom: 8px;"%>
  <h1>Customer List</h1>
  <table class="table table-bordered table-striped table-condensed">
    <thead>
      <th>Customer Name</th>
      <th>Contact Info</th>
      <!-- <th>Address</th> -->
      <th>Action</th>
    </thead>  
    <tbody>
      <% @customers.each do |customer|%>
        <tr>
          <td><%= link_to customer.name, customer_path(customer)%></td>
          <td><%= customer.phone %></td>
          <td>
            <%#= link_to "show", project_path(project), class: "btn btn-default btn-sm" %>
            <%#= link_to "Download Detailed Report", detail_report_project_path(project, { format: :pdf}), class: "btn btn-sm btn-info" %>
            <%#= link_to "Send Incident Report", project_incidents_path(project), class: "btn btn-sm btn-primary" %>
            <%#= link_to "Incident Report", "#", class: "btn btn-xs btn-success" %>
            <!-- project_incidents_path(project) -->
            <%#= link_to "Checklists", "#", class: "btn btn-xs btn-info"%>       
            <!-- report_project_path(project) -->
            <%= link_to "users", users_customer_path(customer), class: "btn btn-xs btn-default" %>
            <!-- users_project_path(project) -->
            <%= link_to "View items",customer_items_path(customer), class: "btn btn-xs btn-success" %>

            <%= link_to "close user",close_customer_customer_path(customer), class: "btn btn-xs btn-warning" %>

            <% if current_user.role == "client" %>
              <%= link_to "Assign to user", assign_customer_customer_path(customer), class: "btn btn-xs btn-primary" %>
            <% end %>  
            <%#= link_to 'Delete', project, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-xs btn-danger" %>
            </td>
        </tr>
      <% end %>   
    </tbody>  
  </table> 
<% else %>
  <b>No Customer Present</b>
<% end %>   

app/views/customers/new.html.erb
<h1 class = "text-center">Create customer</h1>
 <%= render "form", :url=>customers_path %> 

app/views/customers/report.html.erb
<h1><%= @project.name %></h1>
<% if @project.present? %>  
  <table class="table table-bordered table-striped table-condensed">
    <thead>
      <!-- <th>Project</th> -->
      <th>User</th>
      <th>30 days Checklists</th>
      <th>60 days Checklists</th>
      <th>90+ day Checklists</th>
    </thead>  
    <tbody>
      <%# @projects.each do |project|%>
        <tr>
          <!-- <td><%#= @project.name %></td> -->
          <td><%= @uname %></td>
          <td>
            <% if @red_30 != true %>
              <%= link_to "#{@days_30}", project_reports_path(@project) %>
            <% else %>
              <%= link_to "#{@days_30}", project_reports_path(@project), style: "color: red;" %>
            <% end %>
          </td>
          <td>
            <% if @red_60 != true %>
              <%= link_to "#{@days_60}", project_reports_path(@project) %>
            <% else %>
              <%= link_to "#{@days_60}", project_reports_path(@project), style: "color: red;" %>
            <% end %>
          </td>
          <td>
            <% if @red_90 != true %>
              <%= link_to "#{@days_90}", project_reports_path(@project) %>
            <% else %>
              <%= link_to "#{@days_90}", project_reports_path(@project), style: "color: red;" %>
            <% end %>
          </td>
        </tr>
      <%# end %>   
    </tbody>  
  </table> 
<% else %>
  <b>No Project Present</b>
<% end %>   

app/views/customers/reports.html.erb
<script type="text/javascript">
  $(document).ready(function(){

    if ( $('#inc_id').length > 0 && $('#inc_id').val() > 0 ){
      window.location.href = '/incidents/'+ $('#inc_id').val() +'/send_new_incident.pdf';
    }

  });  
</script>
<%#= hidden_field_tag 'active_class', 'all_projects'%>
<% if @reports.present? %>  
  <table class="table table-bordered table-striped table-condensed">
    <thead>
      <th>Name</th>
      <th>Action</th>
    </thead>  
    <tbody>
      <% @reports.each do |report|%>
        <tr>
          <td><%= report.name %></td>
          <td>
            <%#= link_to "show", project_path(project), class: "btn btn-default btn-sm" %>
            <%= link_to "View Report", "#", class: "btn btn-xs btn-primary" %>
            <%= link_to 'Destroy', report_path(report, {project_id: @project}), data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-xs btn-danger" %>
            </td>
        </tr>
      <% end %>   
    </tbody>  
  </table> 
  <% if params[:inc].present? && Incident.find(params[:inc]).present? && Incident.find(params[:inc]).downloaded.blank? %>
    <%= hidden_field_tag :inc_id, params[:inc] %>
  <% end %>
<% else %>
  <b>No Project Present</b>
<% end %>   

app/views/customers/show.html.erb
<style type="text/css">
	.td_width{
		width: 20%;
	}
</style>


<% if @customer.present? %>
<div class="container-fluid">
	<div class="container" >
		<div class="content" style="width:55%;">
			<div class="row">
				<div class="login-form">
					<div class="alert alert-info">
						<%= link_to 'Edit', edit_customer_path(@customer), :class=>"btn btn-primary btn-xs pull-right" %>
						<h4>Customer details</h4>
					</div>
					<table class="table table-striped">
						<tr>
							<td class="td_width" style="background-color: lightgray;">bill_of_laden</td>
							<td><%= @customer.bill_of_laden || ''%></td>
						</tr>
						<tr>
							<td class="td_width" style="background-color: lightgray;">Name</td>
							<td><%= @customer.name || ''%></td>
						</tr>
						<tr>
							<td class="td_width" style="background-color: lightgray;">Phone</td>
							<td><%= @customer.phone || ''%></td>
						</tr>
						<tr>
							<td class="td_width" style="background-color: lightgray;">Loading Address</td>
							<td><%= @customer.loading_address || ''%></td>
						</tr>
						<tr>
							<td class="td_width" style="background-color: lightgray;">Destination Address</td>
							<td><%= @customer.destination_address || ''%></td>
						</tr>
						<tr>
							<td class="td_width" style="background-color: lightgray;">Tag lot #</td>
							<td><%= @customer.tag_lot_number || ''%></td>
						</tr>
						<tr>
							<td class="td_width" style="background-color: lightgray;">Tag lot color</td>
							<td><%= @customer.tag_lot_color || ''%></td>
						</tr>
						<tr>
							<td class="td_width" style="background-color: lightgray;">Agent name</td>
							<td><%= @customer.agent_name || ''%></td>
						</tr>
						<tr>
							<td class="td_width" style="background-color: lightgray;">Pickup date</td>
							<td><%= @customer.date_of_pickup || ''%></td>
						</tr>
						<tr>
							<td class="td_width" style="background-color: lightgray;">Charges</td>
							<td><%= @customer.charges || ''%></td>
						</tr>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<% end %>
<%= link_to '<< Back', customers_path, :class=>"btn btn-primary btn-xs" %>

app/views/customers/tempshow.html.erb
<script type="text/javascript">
	$(document).ready(function(){

		$('.answer_status').click(function(){
			var $this = $(this);
			$.ajax({
	          type: 'get',
	          url: '/projects/'+ $('#project_id').val() +'/answers/' + $this.attr('data-id') + '/check_answer',
	          dataType: 'json',
	          data: {
	          	id: $this.attr('data-id')
	          },
	          success :function(data){
	          	if(data == true)
	          	{
	          		bootbox.prompt("Please Enter Reason?", function(result) {                
					  if (result === null) {                                             
					    // Example.show("Prompt dismissed");                              
					  } else {
						$.ajax({
				          type: 'patch',
				          url: '/projects/'+ $('#project_id').val() +'/answers/' + $this.attr('data-id'),
				          dataType: 'json',
				          data: {
				          	status: $this.val(),
				          	note: result
				          }
			        	});  	
					  }
					});
	          	}else{
					$.ajax({
			          type: 'patch',
			          url: '/projects/'+ $('#project_id').val() +'/answers/' + $this.attr('data-id'),
			          dataType: 'json',
			          data: {
			          	status: $this.val(),
			          	id: $this.attr('data-id')
			          }
		        	});
	          	}
	          }
	        });
		});
        ///////submit button click
		$(".update-answer").click(function(e){
			// alert("sdssd");
			e.preventDefault();
			var ansid = $(this).attr('id');
			// alert(ansid);
			// var pid =  $("#answer_project").val();
			// var ans = $("#answer_answer-"+ansid).val();
			var token =  $('meta[name="csrf-token"]').attr('content');
			var form = $(this).parents('form');
			console.log(form);
			var url = form.attr('action');
			form.ajaxSubmit({
				url: url,
				dataType: 'json',
				type: 'patch',
				data: {
		            'authenticity_token' : $('meta[name="csrf-token"]').attr('content')
		        },
		        success: function (data) {
		        	// alert("sasasasasass");
		        	$(".save-span-"+ansid).removeClass("hidden");
 	             	$("#notes-"+ansid).val('');
 	             	// $("#answer_file").val('');
                }
			});
			      		
		});
	});
</script>
<%= hidden_field_tag :project_id, @project.id %>
<table class="table table-bordered table-striped table-condensed">
	<thead>
    <th>Name</th>
    <th>Contact Info</th>
    <th>Address</th>
    <th>Action</th>
	</thead>	
	<tbody>
		<tr>
			<td><%= @project.name %></td>
			<td><%= @project.contact_info %></td>
			<td><%= @project.address %></td>
			<td>
            	<%= link_to "Edit", edit_project_path(@project), class: "btn btn-default btn-sm" %>
            	            <%= link_to "View Checklists", project_reports_path(@project), class: "btn btn-sm btn-warning" %>

				<%= link_to "Download detail report", detail_report_project_path(@project, { format: :pdf}), class: "btn btn-sm btn-info" %>
				<%= link_to "Send incident", new_project_incident_path(@project), class: "btn btn-sm btn-primary" %>
				<%= link_to "View incidents", project_incidents_path(@project), class: "btn btn-sm btn-success" %>
            	<%= link_to 'Delete', @project, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-sm btn-danger" %>
				</td>

		</tr>	
	</tbody>	
</table>	

<%#= form_for @project, html: { class: 'well', role: 'form'} do |f| %>

	<fieldset>
	  <h2 class="text-center"><strong><u>Detailed View of <%= @project.name %></u></strong> </h2>
	  <br/>
		<%#= f.hidden_field :enable_answers_validation, value: true %>
	  	<% @categories.each do |c| %>
			<h3><strong><u><%= c.name %></u></strong></h3>
			<% c.questions.each do |q| %>
				<div class="form-group">		
					<%= "#{q.body}" %>
		      		<% answer = @answers.find_by(question_id: q.id) %>
				     	<div class="row">
					     	<% GlobalConstants::Answers::STATUSES.each do |st| %> 
						      	<div class="col-sm-3">
						      		<%= radio_button_tag "status#{answer.id}", st[1], answer_radio_status(answer.status, st[1]), class: "answer_status", data: { id: answer.id } %>
						      		<%= label "status#{answer.id}_#{st[1]}", st[0] %>	
						      	</div> 
					      	<% end %>
				        </div>
				    <br/>
		    	</div>
		    	<div class="" style="margin-right: 0px;margin-left: 14px;">
		       	<%= render partial: "notes", :locals => {:@answer1 => answer, :@project=>@project} %>
		       </div>
			<% end %>
		<% end %>
	</fieldset>
<%# end %>

app/views/customers/users.html.erb
<% if @users.present? %>
	<h3><%= @customer.name %></h3>
	<table class="table table-bordered table-striped table-condensed">
		<thead>
			<th>User</th>
			<th>Email</th>
			<th>Action</th>
		</thead>	
		<tbody>
			<% @users.each do |user| %>
				<tr>
					<td><a href="<%= user_path(user) %>"><%= user.first_name || user.last_name || ''%></a></td>
					<td><%= user.email %></td>
					<td>
						<!-- <a href="<%= edit_user_registration_path(user.id) %>" class="btn btn-primary btn-sm">Edit</a> -->
						<%= link_to 'Unassign',unassign_customer_path(@customer,{uid: user.id}), :class=>"btn btn-primary btn-xs" %>
					</td>
				</tr>	
			<% end %>
		</tbody>	
	</table>	
<% else %>
	<div class="alert alert-info text-center">
		No user has been found.
	</div>	
<% end %>

<%#= link_to "Assign to user", assign_project_project_path(@project), class: "btn btn-xs btn-primary" %>