config/routes.rb
CarrierApp::Application.routes.draw do

  post "/users" => "users#create"
  get "/users/sign_out" => "sessions#destroy"

  devise_for :users, :controllers => {:registrations => 'registrations', sessions: "sessions" }
  
  devise_scope :user do
    match "/users/sign_in.:format" => "sessions#create", via: :options
    get "/users/sign_in.:format" => "sessions#create"
  end

  

    root 'home#index'
    resources :invitations
    resources :users do 
      collection do
        get 'add_user'
        post 'adduser'
      end
    end

    resources :customers do
      member do
        get 'users'
        get 'assign_customer'
        get 'unassign'
        get 'close_customer'
      end
      collection do 
        get 'closedCustomers'
        post 'add_users'
      end
      resources :items do 
        member do
          patch 'upload_image'
        end
        collection do
          get 'empty_item'
        end
      end
    end

    
    resources :questions, only: [:index] do
      member do
        get 'get_question'
      end
      resources :reports, only: [] do 
        member do
          get 'get_answer'
          get 'getanswerid'
        end
      end
    end
    resources :categories, only: [:index] do 
      member do
        get 'questions'
      end
    end
    resources :projects do
      member do 
        get 'detail_report'
        get 'assign_project'
        get 'report'
        get 'users'
        get 'unassign'
        get 'submit_report'
        patch 'update_answer'
        get 'categories'
        get 'checklist'
      end
      collection do 
        post 'add_users'
      end
      resources :answers, only: [:update] do
        member do
           patch 'update_answer'
           get 'check_answer'  
        end
      end
      resources :reports do 
        member do
          get 'detail_report'
        end
      end
      resources :incidents, only: [:new, :create, :index, :show]
    end

    resources :reports, only: [] do
      member do
        get 'answers'
      end 
      resources :categories, only: [] do
        member do
          get 'answers'
        end
      end
    end

    resources :incidents, only: [] do
      member do 
        get 'send_new_incident'
        post 'send_email'
        get 'send_email'
      end
    end

end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :customer

	mount_uploader :file1, FileUploader
	mount_uploader :file2, FileUploader
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :authenticate_user!
	# before_action :check_user
	# before_action :set_project, only: [:edit, :update, :destroy, :detail_report]
	respond_to :html, :json, only: [:index, :new, :create, :edit, :update, :show, :destroy,:assign_project,:add_users,:reports,:users]

	def index
	
		@customer = Customer.find(params[:customer_id])
		@items = @customer.items.where(cn: true)
		respond_with @items
	end

	def new
		@customer = Customer.find(params[:customer_id])
		@item = @customer.items.build
		@count = @customer.items.count
		respond_with @item
	end

	def create
		customer = Customer.find(params[:customer_id])
		if params[:itemid].present?
			@item = Item.find(params[:itemid])
		else
			@item = customer.items.build
		end
		# @item.item_number = params[:item][:item_number]
		@count = customer.items.count
		@item.item_number = @count+1
		@item.article = params[:item][:article]
		@item.description_at_origin = params[:item][:description_at_origin]
		@item.driver = params[:item][:driver]
		@item.warehouse_cross = params[:item][:warehouse_cross]
		@item.warehouse = params[:item][:warehouse]
		@item.desr_symbole = params[:item][:desr_symbole]
		@item.shipper = params[:item][:shipper]
		@item.exception_symbol = params[:item][:exception_symbol]
		@item.location_symbol = params[:item][:location_symbol]
		@item.exception = params[:item][:exception]
		@item.file1 = params[:item][:file1]
		@item.file2 = params[:item][:file2]

		respond_to do |format|
			if @item.save
				@item.cn = true
				@item.save!
				customer.items.where(cn: false).destroy_all
				format.html { redirect_to customer_items_path(customer), success: "Item successfully created." }
		        format.json {  render json: :true}
			else
				format.html { render action: 'new' }
		        format.json { render json: :false}
			end
		end
	end


	def edit
		@item = Item.find(params[:id])
		@customer = Customer.find(params[:customer_id])
		@count = @customer.items.count
		respond_with @item
	end

	def update
		@customer = Customer.find(params[:customer_id])
		@item = Item.find(params[:id])
		@item.update_attributes(params_item)
		respond_to do |format|
			format.html { redirect_to customer_items_path(@customer), success: "Item successfully updated." }
	        format.json {  render json: :true}
		end
	end 

	def destroy
		@item = Item.find(params[:id])
		@customer = Customer.find(params[:customer_id])
		@item.destroy if @item.present?
		flash[:success] = "Successfully deleted."
		respond_to do |format|
			format.html { redirect_to customer_items_path(@customer), success: "Item successfully updated." }
	        format.json {  render json: :true}
		end
	end

	def show   # it is using to show details of the closed customer items
		@customer = Customer.find(params[:customer_id])
		@item = Item.find(params[:id])
		respond_with @item 
	end

	def upload_image   #upload image through app
		@customer = Customer.find(params[:customer_id])
		@item = Item.find(params[:id])
		# if params[:item][:itemId].present?
		# 	@item = Item.find(params[:itemId])
		# else
		# 	@item = @customer.items.build
		# end
		if params[:item][:file1].present?
			@item.file1 = uploaded_picture(params[:item][:file1]) if params[:item][:file1].present?
			@item.save!
			@url = @item.file1_url
		elsif params[:item][:file2].present?
			@item.file2 = uploaded_picture(params[:item][:file2]) if params[:item][:file2].present?
			@url = @item.file2_url
		end
		
		return render :json=>{url: @url}
	end

	def empty_item    # this function using only for mob app to create empty item
		@customer = Customer.find(params[:customer_id])
		@count = @customer.items.count
		item = @customer.items.build
		item.save!
		item.item_number = @count+1
		item.save!
		return render :json=> item
	end




	private

	def params_item
		params.require(:item).permit(:article,:item_number,:description_at_origin,:driver,:warehouse,:warehouse_cross,:shipper,:desr_symbole,:exception_symbol,:location_symbol,:file1,:file2,:exception)
	end

  	def uploaded_picture(base64)

	    tempfile = Tempfile.new ['upload', '.jpg']
	    tempfile.binmode
	    tempfile.write(Base64.decode64(base64))

	    # ActionDispatch::Http::UploadedFile.new(tempfile: tempfile,
	    #   filename: 'upload.jpg')
		tempfile
	end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<style type="text/css">
  .select{
    width: 100% !important;
    height: 29px;
    background-color: #fff;
  }
</style>
<%= hidden_field_tag 'active_class', 'create_project'%>
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <%= form_for @item, :url=> url, html: { class: 'well form-horizontal', role: 'form'} do |f| %>

      <fieldset>
        <% if @item.errors.any? %>
          <div class="alert alert-danger">
            <h4><%= pluralize(@item.errors.count, "error") %> prohibited this project from being saved:</h4>

            <ul>
            <% @item.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label "Item #", class: "col-sm-3 control-label" %>
          <div class="col-sm-9" style="margin-top: 1.5%;">
            <%= @count+1 %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Article", class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :article, autofocus: true, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Description at origin", class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :description_at_origin, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Warehouse cross", class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :warehouse_cross, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Driver", class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :driver, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Warehouse", class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :warehouse, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Shipper", class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :shipper, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Exception", class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :exception, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Desr symbol", class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%#= f.text_field :desr_symbole, class: "form-control" %>
            <%= f.select :desr_symbole, GlobalConstants::Options::DESCR, class: "select" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Exception symbol", class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%#= f.text_field :exception_symbol, class: "form-control" %>
            <%= f.select :exception_symbol, GlobalConstants::Options::EXCEP, class: "select" %>
          </div>
        </div>

         <div class="form-group">
          <%= f.label "Location symbol", class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%#= f.text_field :location_symbol, class: "form-control" %>
            <%= f.select :location_symbol, GlobalConstants::Options::LOCATION, class: "select" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "Image 1", class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.file_field :file1 %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label "Image 2", class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.file_field :file2 %>
          </div>
        </div>
      </fieldset>

      <div class="col-sm-offset-3">
        <%= f.submit 'Save', class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/items/edit.html.erb
<h1 class = "text-center">Create Item</h1>
 <%= render partial: "form", :locals=>{:url=>customer_item_path(@customer,@item)} %> 

app/views/items/index.html.erb
<script type="text/javascript">
  $(document).ready(function(){

    if ( $('#inc_id').length > 0 && $('#inc_id').val() > 0 ){
      window.location.href = '/incidents/'+ $('#inc_id').val() +'/send_new_incident.pdf';
    }

  });  
</script>
<%= hidden_field_tag 'active_class', 'all_projects'%>
<div class="alert alert-info">
  <% if !@customer.close.present? %>
    <%= link_to "Add item",new_customer_item_path(@customer) , class: "btn btn-xs btn-primary pull-right" %>
  <% end %>
  <strong>Customer Name:</strong> <%= @customer.name %><br/>
  <strong>Bill of Laden #:</strong> <%= @customer.bill_of_laden %>
</div>

<% if @items.present? %>  
  <%#= link_to "Reports", report_projects_path, class: "btn btn-sm btn-info pull-right" ,style: "margin-bottom: 8px;"%>
  <h1>Item List</h1>
  <table class="table table-bordered table-striped table-condensed">
    <thead>
      <th>Item #</th>
      <th>Article</th>
      <th>Description at origin</th>
      <th>Driver</th>
      <th>Warehouse</th>
      <th>Shipper</th>
      <% if !@customer.close.present? %>
        <th>Action</th>
      <% end %>
    </thead>  
    <tbody>
      <% @items.each do |item|%>
        <tr>
          <td><%= link_to item.item_number,  customer_item_path(@customer,item) %></td>
          <td><%= item.article %></td>
          <td><%= item.description_at_origin %></td>
          <td><%= item.driver %></td>
          <td><%= item.warehouse %></td>
          <td><%= item.shipper %></td>
          <td>
            <%#= link_to "show", project_path(project), class: "btn btn-default btn-sm" %>
            <%#= link_to "Download Detailed Report", detail_report_project_path(project, { format: :pdf}), class: "btn btn-sm btn-info" %>
            <%#= link_to "Send Incident Report", project_incidents_path(project), class: "btn btn-sm btn-primary" %>
            <%#= link_to "Incident Report", "#", class: "btn btn-xs btn-success" %>
            <!-- project_incidents_path(project) -->
            <% if !@customer.close.present? %>
              <%= link_to "view details",customer_item_path(@customer,item) , class: "btn btn-xs btn-success" %>
              <%= link_to "Edit",edit_customer_item_path(@customer,item) , class: "btn btn-xs btn-primary" %>
              <%= link_to 'Delete',customer_item_path(@customer,item), data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-xs btn-danger" %>
            <% else %>
              <%= link_to "view detail",customer_item_path(@customer,item) , class: "btn btn-xs btn-primary" %>
            <% end %>
            <%# if current_user.role == "client" %>
              <%#= link_to "Assign to user", assign_project_project_path(project), class: "btn btn-xs btn-primary" %>
            <%# end %>  
            </td>
        </tr>
      <% end %>   
    </tbody>  
  </table> 
<% else %>
  <b>No Item Present</b>
<% end %>  

app/views/items/new.html.erb
<h1 class = "text-center">Create Item</h1>
 <%= render partial: "form", :locals=>{:url=> customer_items_path(@customer)} %> 

app/views/items/show.html.erb
<style type="text/css">
	.td_width{
		width: 20%;
	}
</style>
<div class="alert alert-info">
  <strong>Customer Name:</strong> <%= @customer.name %><br/>
  <strong>Bill of Laden #:</strong> <%= @customer.bill_of_laden %>
</div>

<% if @item.present? %>
<div class="container-fluid">
	<div class="container" >
		<div class="content" style="width:55%;">
			<div class="row">
				<div class="login-form">
					<h4>Item details</h4>
					<table class="table table-striped">
						<tr>
							<td class="td_width" style="background-color: lightgray;">Item #</td>
							<td><%= @item.item_number || ''%></td>
						</tr>
						<tr>
							<td class="td_width" style="background-color: lightgray;">Description at origin</td>
							<td><%= @item.description_at_origin || ''%></td>
						</tr>
						<tr>
							<td class="td_width" style="background-color: lightgray;">Warehouse cross</td>
							<td><%= @item.warehouse_cross || ''%></td>
						</tr>
						<tr>
							<td class="td_width" style="background-color: lightgray;">Driver</td>
							<td><%= @item.driver || ''%></td>
						</tr>
						<tr>
							<td class="td_width" style="background-color: lightgray;">Warehouse</td>
							<td><%= @item.warehouse || ''%></td>
						</tr>
						<tr>
							<td class="td_width" style="background-color: lightgray;">Shipper</td>
							<td><%= @item.shipper || ''%></td>
						</tr>
						<tr>
							<td class="td_width" style="background-color: lightgray;">Exception</td>
							<td><%= @item.exception || ''%></td>
						</tr>
						<tr>
							<td class="td_width" style="background-color: lightgray;">Desr symbol</td>
							<td><%= @item.desr_symbole || ''%></td>
						</tr>
						<tr>
							<td class="td_width" style="background-color: lightgray;">Exception symbol</td>
							<td><%= @item.exception_symbol || ''%></td>
						</tr>
						<tr>
							<td class="td_width" style="background-color: lightgray;">Location symbol</td>
							<td><%= @item.location_symbol || ''%></td>
						</tr>

						<tr>
							<td class="td_width" style="background-color: lightgray;">Photo 1</td>
							<td><% if @item.file1.present? %>
								<%= link_to "click here" ,"http://localhost:3000"+@item.file1.url, :target=>"blank"%>
								<% else %>
								:-(
								<% end %>
							</td>
						</tr>
						<tr>
							<td class="td_width" style="background-color: lightgray;">Photo 2</td>
							<td>
								<% if @item.file2.present? %>
								<%= link_to "click here" ,"http://localhost:3000"+@item.file2.url, :target=>"blank"%>
								<% else %>
								:-(
								<% end %>
							</td>
						</tr>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<% end %>
<%= link_to '<< Back', customer_items_path(@customer), :class=>"btn btn-primary btn-xs" %>