config/routes.rb
CarrierApp::Application.routes.draw do

  post "/users" => "users#create"
  get "/users/sign_out" => "sessions#destroy"

  devise_for :users, :controllers => {:registrations => 'registrations', sessions: "sessions" }
  
  devise_scope :user do
    match "/users/sign_in.:format" => "sessions#create", via: :options
    get "/users/sign_in.:format" => "sessions#create"
  end

  

    root 'home#index'
    resources :invitations
    resources :users do 
      collection do
        get 'add_user'
        post 'adduser'
      end
    end

    resources :customers do
      member do
        get 'users'
        get 'assign_customer'
        get 'unassign'
        get 'close_customer'
      end
      collection do 
        get 'closedCustomers'
        post 'add_users'
      end
      resources :items do 
        member do
          patch 'upload_image'
        end
        collection do
          get 'empty_item'
        end
      end
    end

    
    resources :questions, only: [:index] do
      member do
        get 'get_question'
      end
      resources :reports, only: [] do 
        member do
          get 'get_answer'
          get 'getanswerid'
        end
      end
    end
    resources :categories, only: [:index] do 
      member do
        get 'questions'
      end
    end
    resources :projects do
      member do 
        get 'detail_report'
        get 'assign_project'
        get 'report'
        get 'users'
        get 'unassign'
        get 'submit_report'
        patch 'update_answer'
        get 'categories'
        get 'checklist'
      end
      collection do 
        post 'add_users'
      end
      resources :answers, only: [:update] do
        member do
           patch 'update_answer'
           get 'check_answer'  
        end
      end
      resources :reports do 
        member do
          get 'detail_report'
        end
      end
      resources :incidents, only: [:new, :create, :index, :show]
    end

    resources :reports, only: [] do
      member do
        get 'answers'
      end 
      resources :categories, only: [] do
        member do
          get 'answers'
        end
      end
    end

    resources :incidents, only: [] do
      member do 
        get 'send_new_incident'
        post 'send_email'
        get 'send_email'
      end
    end

end

app/models/report.rb
class Report < ActiveRecord::Base

	belongs_to :project
	has_many :answers, dependent: :destroy
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	respond_to :html, :json
	def index
		id = []
		@good_report = []
		@project = Project.find(params[:project_id])
		@reports = @project.reports.order("created_at ASC")
		@reports.each do |rep|
			if !rep.answers.where(status: [0,2,3]).present?
				id << rep.id
			end	
		end
		if id.length > 0
			# puts "000"*90
			@reports = @project.reports.where.not(id: id)			
			@good_report = @project.reports.where(id: id)
		end
		# @answers = @project.reports.answers
		respond_with :obj => {:@project=> @project,:@reports=>@reports, :@good_report=> @good_report }
		# respond_with
	end


	def get_answer
		# @question = Question.find(params[:question_id])
		@answers  = Answer.where(question_id: params[:question_id], report_id: params[:id])
		# @answers  = @question.answers
		respond_with @answers
	end

	def getanswerid
		answer  = Answer.where(question_id: params[:question_id], report_id: params[:id])
		# @answers  = @question.answers
		respond_with answer
	end

	def destroy
		report = Report.find(params[:id])
		report.destroy
		@project = Project.find(params[:project_id])
		respond_to do |format|
	        format.html { redirect_to project_reports_path(@project), success: 'Users add successfully.' }
	        format.json { render :json=> true }
	    end
	end

	def show
		@report = Report.find(params[:id])
		@project = @report.project
		@categories = Category.all.includes(:questions)
		@answers = @report.answers
		# respond_with :obj => {project: @project, categories: @categories, answers: @answers}
	end

	def answers
		@report = Report.find(params[:id])
		@answers = @report.answers
		respond_with @answers
	end

	def detail_report
		@report = Report.find(params[:id])
  		respond_to do |format|
    		format.html
    		format.json { render :json=> true} 
    		format.pdf do
      		pdf = ReportDetailPdf.new(@report, view_context)
      		send_data pdf.render, filename: "(#{@report.name}) report.pdf", type: "application/pdf", disposition: "attachment"
    		end
 		end
	end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/index.html.erb
<script type="text/javascript">
  $(document).ready(function(){

    if ( $('#inc_id').length > 0 && $('#inc_id').val() > 0 ){
      window.location.href = '/incidents/'+ $('#inc_id').val() +'/send_new_incident.pdf';
    }

  });  
</script>
<%#= hidden_field_tag 'active_class', 'all_projects'%>
<% if @reports.present? %>  
  <h1><%= @project.name %></h1>
  <table class="table table-bordered table-striped table-condensed">
    <thead>
      <th>Date</th>
      <th>User</th>
      <th>Action</th>
    </thead>  
    <tbody>
      <% @reports.each do |report|%>
        <tr>
          <td>
            <% if report.answers.where(status: 2).present? %>
              <span style="color: red;"><%= "#{report.created_at.strftime("%m/%d/%Y")}" %></span>
            <% else %>
              <%= "#{report.created_at.strftime("%m/%d/%Y")}" %>
            <% end %>
          </td>
          <td>
            <%#  reports = @project.reports.where("reports.created_at >= ? AND reports.created_at <= ?", report.created_at.to_date, "#{report.created_at.to_date} 23:59:59.996") %>
              <%# reports && reports.each do |rep| %> 
               <% user = User.find(report.user_id) %> 
                <%# if user.present? %>
                  <%= user.first_name || user.last_name || '' %>
                <%# end %>
              <%# end %>
            </td>
          <td>
            <%= link_to "Download Checklist",detail_report_project_report_path(@project,report ,{ format: :pdf}), class: "btn btn-success btn-xs" %>
            <%= link_to "View Checklist", project_report_path(@project,report), class: "btn btn-xs btn-primary" %>
            <%= link_to 'Delete', project_report_path(@project,report), data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-xs btn-danger" %>
            </td>
        </tr>
      <% end %>   
    </tbody>  
  </table> 
  <% if params[:inc].present? && Incident.find(params[:inc]).present? && Incident.find(params[:inc]).downloaded.blank? %>
    <%= hidden_field_tag :inc_id, params[:inc] %>
  <% end %>
<% else %>
  <div class="alert alert-info">No report has been found.</div>
<% end %>
<%= link_to "< Back",report_project_path(@project), class: "btn btn-xs btn-primary" %>   

app/views/reports/show.html.erb
<script type="text/javascript">
	$(document).ready(function(){

		$('.send_email_button').click(function(){
			$(".sent_email").addClass("hidden");
			var $this = $(this);
			var q_id = $this.attr("id");
			var email = $("#emailTxt").val();
			var rep_id = $("#report_report_id").val();
			
			var emailReg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
			if( !emailReg.test( email ) ) 
			{
			    alert("Please enter correct email address")
			} else {
			    // return true;
				$.ajax({
		          type: 'get',
		          url: '/incidents/'+ rep_id +'/send_email',
		          dataType: 'json',
		          data: {
		          	email: email,
		          	qid: q_id
		          },
		          success :function(data){
		          	if(data == 'true')
		          	{
		          		// alert("email sent");
		          		$(".sent_email").removeClass("hidden");
		          		$("#emailTxt").val('')
		          	}
		          	else
		          	{
		          		alert("email not sent");
		          	}
		          }
		        }); // end of ajax
			}
		});


	$('.answer_status').click(function(){
			var $this = $(this);
			$.ajax({
	          type: 'get',
	          url: '/projects/'+ $('#project_id').val() +'/answers/' + $this.attr('data-id') + '/check_answer',
	          dataType: 'json',
	          data: {
	          	id: $this.attr('data-id')
	          },
	          success :function(data){
	          	if(data == true)
	          	{
	          		bootbox.prompt("Please Enter Reason?", function(result) {                
					  if (result === null) {                                             
					    // Example.show("Prompt dismissed");                              
					  } else {
						$.ajax({
				          type: 'patch',
				          url: '/projects/'+ $('#project_id').val() +'/answers/' + $this.attr('data-id'),
				          dataType: 'json',
				          data: {
				          	status: $this.val(),
				          	note: result
				          }
			        	});  	
					  }
					});
	          	}else{
					$.ajax({
			          type: 'patch',
			          url: '/projects/'+ $('#project_id').val() +'/answers/' + $this.attr('data-id'),
			          dataType: 'json',
			          data: {
			          	status: $this.val(),
			          	id: $this.attr('data-id')
			          }
		        	});
	          	}
	          }
	        });
	});

	});
</script>
<%= hidden_field_tag :report_id, @report.id %>
<%= hidden_field_tag :project_id, @report.project.id %>
<%= link_to "<< Back",project_reports_path(@project) %>
<br/>
<h1><%= @project.name %></h1>
<!-- <table class="table table-bordered table-striped table-condensed">
    <thead>
      <th>Name</th>
      <th>Action</th>
    </thead>  
    <tbody>
        <tr>
          <td><%= @report.name %></td>
          <td>
            <%#= link_to "show", project_path(project), class: "btn btn-default btn-sm" %>
            <%#= link_to 'Destroy', "#", data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-xs btn-danger" %>
            </td>
        </tr>
    </tbody>  
</table>  -->

<%= form_for @report,:url=> edit_project_report_path(@project,@report), html: { class: 'well', role: 'form'} do |f| %>

	<fieldset>
	  <h2 class="text-center"><strong><u><%= @report.created_at.to_date %> Checklist</u></strong> </h2>
	  <br/>
	  <div class="alert alert-success sent_email hidden" >Email has been successfully sent.</div>
		<%= f.hidden_field :enable_answers_validation, value: true %>
		<%= f.hidden_field :report_id,value:@report.id %>

	  	<% @categories.each do |c| %>
			<h3><strong><u><%= c.name %></u></strong></h3>
			<% c.questions.each do |q| %>
				<div class="form-group">		
					<% answer = @answers.find_by(question_id: q.id) %>
		            <% if(answer.status == 2)  %>
						<%= f.label q.body, class: "control-label", style: "color: red" %>
					<% else %>
						<%= f.label q.body, class: "control-label" %>
			     	<% end %>
			     	<div class="row">
				     	<% GlobalConstants::Answers::STATUSES.each do |st| %> 
					      	<div class="col-sm-3">
					      		<%= radio_button_tag "status#{answer.id}", st[1], answer_radio_status(answer.status, st[1]), class: "answer_status", data: { id: answer.id } %>
					      		<%= label "status#{answer.id}_#{st[1]}", st[0] %>	
					      	</div> 
				        <% end %>
				        <br/>
				          <div class="control-group col-xs-3">
				            <!-- <label class="control-label">Email</label>   -->
				            <input type="text" id="emailTxt" name="emailTxt" />
				            <%=link_to  "Send","javascript:void(0)" ,class: "btn btn-xs btn-primary send_email_button", :id=> "#{q.id}" %>
				          </div>
			        <br/>
		    	</div>
			<% end %>
		<% end %>
	</fieldset>
<% end %>